[package]
name = "resize-image"
version = "0.1.0"
description = ""
authors = ["Jozef Podlecki"]
edition = "2024"
rust-version = "1.90.0"

[dependencies]
image = "0.25.8"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.100"